# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vO7i2KGz-575eRyDQvbpqK3gkaHWCSjd
"""

#Yarn
!npm -g install yarn
!yarn add axios
import subprocess
addpackage='axios'
rr=f'add package {addpackage}'
try:
  subprocess.run(rr,shell=True,check=True)
  print('succesfuly installed axios using yarn')
except subprocess.CalledProcessError as e:
  print('error')



